filebeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: false

filebeat.inputs:
  - type: filestream
    id: docker-suricata
    paths:
      - /var/log/suricata/eve.json

processors:
  - add_cloud_metadata: ~
  - add_docker_metadata: ~

setup.kibana:
  host: "http://kibana:5601"
  username: "elastic"
  password: "${ELASTIC_PASSWORD}"

output.elasticsearch:
  hosts: ["https://es01:9200"]
  username: "elastic"
  password: "${ELASTIC_PASSWORD}"
  ssl.certificate_authorities: ["/usr/share/filebeat/config/certs/ca/ca.crt"]

ssl:
  verification_mode: "none"
